# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Accessory(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    SUNGLASSES = "Sunglasses"
    EARRINGS = "Earrings"
    BRACELETS = "Bracelets"
    NECKLACES = "Necklaces"
    WATCHES = "Watches"
    BAGS = "Bags"
    DUPATTA = "Dupatta"
    CAPS = "Caps"
    RINGS = "Rings"
    ANKLETS = "Anklets"
    def __init__(self):  # noqa: E501
        """Accessory - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Accessory':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Accessory of this Accessory.  # noqa: E501
        :rtype: Accessory
        """
        return util.deserialize_model(dikt, cls)
