# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AuthLoginPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, email_id=None, password=None):  # noqa: E501
        """AuthLoginPostRequest - a model defined in OpenAPI

        :param email_id: The email_id of this AuthLoginPostRequest.  # noqa: E501
        :type email_id: str
        :param password: The password of this AuthLoginPostRequest.  # noqa: E501
        :type password: str
        """
        self.openapi_types = {
            'email_id': str,
            'password': str
        }

        self.attribute_map = {
            'email_id': 'emailId',
            'password': 'password'
        }

        self._email_id = email_id
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'AuthLoginPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _auth_login_post_request of this AuthLoginPostRequest.  # noqa: E501
        :rtype: AuthLoginPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email_id(self):
        """Gets the email_id of this AuthLoginPostRequest.


        :return: The email_id of this AuthLoginPostRequest.
        :rtype: str
        """
        return self._email_id

    @email_id.setter
    def email_id(self, email_id):
        """Sets the email_id of this AuthLoginPostRequest.


        :param email_id: The email_id of this AuthLoginPostRequest.
        :type email_id: str
        """

        self._email_id = email_id

    @property
    def password(self):
        """Gets the password of this AuthLoginPostRequest.


        :return: The password of this AuthLoginPostRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this AuthLoginPostRequest.


        :param password: The password of this AuthLoginPostRequest.
        :type password: str
        """

        self._password = password
