# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ConnectionsAddPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None):  # noqa: E501
        """ConnectionsAddPostRequest - a model defined in OpenAPI

        :param user_id: The user_id of this ConnectionsAddPostRequest.  # noqa: E501
        :type user_id: str
        """
        self.openapi_types = {
            'user_id': str
        }

        self.attribute_map = {
            'user_id': 'userId'
        }

        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'ConnectionsAddPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _connections_add_post_request of this ConnectionsAddPostRequest.  # noqa: E501
        :rtype: ConnectionsAddPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self):
        """Gets the user_id of this ConnectionsAddPostRequest.


        :return: The user_id of this ConnectionsAddPostRequest.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this ConnectionsAddPostRequest.


        :param user_id: The user_id of this ConnectionsAddPostRequest.
        :type user_id: str
        """

        self._user_id = user_id
