# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.accessory import Accessory
from openapi_server.models.bottomwear import Bottomwear
from openapi_server.models.footwear import Footwear
from openapi_server.models.single_piece import SinglePiece
from openapi_server.models.topwear import Topwear
from openapi_server import util

from openapi_server.models.accessory import Accessory  # noqa: E501
from openapi_server.models.bottomwear import Bottomwear  # noqa: E501
from openapi_server.models.footwear import Footwear  # noqa: E501
from openapi_server.models.single_piece import SinglePiece  # noqa: E501
from openapi_server.models.topwear import Topwear  # noqa: E501

class ItemCategory(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """ItemCategory - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ItemCategory':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Item_category of this ItemCategory.  # noqa: E501
        :rtype: ItemCategory
        """
        return util.deserialize_model(dikt, cls)
