# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Time(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DAY = "day"
    NIGHT = "night"
    def __init__(self):  # noqa: E501
        """Time - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Time':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Time of this Time.  # noqa: E501
        :rtype: Time
        """
        return util.deserialize_model(dikt, cls)
