# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Topwear(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    T_SHIRTS = "T-Shirts"
    SHIRTS = "Shirts"
    SWEATSHIRTS = "Sweatshirts"
    JACKETS = "Jackets"
    BLAZERS = "Blazers"
    KURTIS = "Kurtis"
    KURTAS = "Kurtas"
    TOPS = "Tops"
    SHRUGS = "Shrugs"
    def __init__(self):  # noqa: E501
        """Topwear - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Topwear':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Topwear of this Topwear.  # noqa: E501
        :rtype: Topwear
        """
        return util.deserialize_model(dikt, cls)
