# coding: utf-8

"""
    Wardrobe Management API

    An API to manage your wardrobe digitally

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.authentication_api import router as AuthenticationApiRouter
from openapi_server.apis.connections_api import router as ConnectionsApiRouter
from openapi_server.apis.items_api import router as ItemsApiRouter
from openapi_server.apis.outfits_api import router as OutfitsApiRouter
from openapi_server.apis.wardrobes_api import router as WardrobesApiRouter

app = FastAPI(
    title="Wardrobe Management API",
    description="An API to manage your wardrobe digitally",
    version="1.0.0",
)

app.include_router(AuthenticationApiRouter)
app.include_router(ConnectionsApiRouter)
app.include_router(ItemsApiRouter)
app.include_router(OutfitsApiRouter)
app.include_router(WardrobesApiRouter)
