# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from enum import Enum

class Occasion(str, Enum):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Occasion - a model defined in OpenAPI

    """
    FESTIVE = "festive"
    WORK = "work"
    PARTY = "party"
    ACTIVE = "active"
    CASUAL = "casual"

