# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional
import uuid  # noqa: F401

from pydantic import UUID4, AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class User(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    User - a model defined in OpenAPI

        user_id: The user_id of this User [Optional].
        name: The name of this User [Optional].
        image: The image of this User [Optional].
        email_id: The email_id of this User [Optional].
        password: The password of this User [Optional].
        connections: The connections of this User [Optional].
        wardrobes: The wardrobes of this User [Optional].
    """

    user_id: UUID4 = Field(alias="user_id", const=True, default_factory=uuid.uuid4)
    name: Optional[str] = Field(alias="name", default=None)
    image: Optional[str] = Field(alias="image", default=None)
    email_id: Optional[EmailStr] = Field(alias="email_id", default=None)
    password: Optional[str] = Field(alias="password", default=None)
    connections: Optional[List[str]] = Field(alias="connections", default=None)
    wardrobes: Optional[List[str]] = Field(alias="wardrobes", default=None)

User.update_forward_refs()
