# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class AuthRegisterPostRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AuthRegisterPostRequest - a model defined in OpenAPI
        name:     The name of this AuthRegisterPostRequest
        email_id: The email_id of this AuthRegisterPostRequest [Optional].
        password: The password of this AuthRegisterPostRequest [Optional].
    """
    name: str
    email_id: EmailStr = Field(alias="email_id", default=None)
    password: str = Field(alias="password", default=None)

AuthRegisterPostRequest.model_rebuild()
