# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ConnectionsAddPostRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConnectionsAddPostRequest - a model defined in OpenAPI

        user_id: The user_id of this ConnectionsAddPostRequest [Optional].
    """

    user_id: Optional[str] = Field(alias="user_id", default=None)

ConnectionsAddPostRequest.model_rebuild()
