# coding: utf-8

"""
    Wardrobe Management API

    An API to manage your wardrobe digitally

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from bson import UuidRepresentation
from fastapi import FastAPI

from apis.authentication_api import router as AuthenticationApiRouter
from apis.connections_api import router as ConnectionsApiRouter
from apis.items_api import router as ItemsApiRouter
from apis.outfits_api import router as OutfitsApiRouter
from apis.wardrobes_api import router as WardrobesApiRouter
from apis.users_api import router as UserApiRouter
from dotenv import dotenv_values
from pymongo import MongoClient

app = FastAPI(
    title="Wardrobe Management API",
    description="An API to manage your wardrobe digitally",
    version="1.0.0",
)

config = dotenv_values(".env")

@app.on_event("startup")
def startup_db_client():
    app.mongodb_client = MongoClient(config["ATLAS_URI"], uuidRepresentation='standard')
    app.database = app.mongodb_client[config["DB_NAME"]]

@app.on_event("shutdown")
def shutdown_db_client():
    app.mongodb_client.close()


app.include_router(AuthenticationApiRouter)
app.include_router(ConnectionsApiRouter)
app.include_router(ItemsApiRouter)
app.include_router(OutfitsApiRouter)
app.include_router(WardrobesApiRouter)
app.include_router(UserApiRouter)
